# Form implementation generated from reading ui file 'ui/Form2.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form2(object):
    def setupUi(self, Form2):
        Form2.setObjectName("Form2")
        Form2.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        Form2.resize(640, 450)
        Form2.setMinimumSize(QtCore.QSize(640, 450))
        Form2.setMaximumSize(QtCore.QSize(640, 450))
        Form2.setAcceptDrops(True)
        self.frame_buttons = QtWidgets.QFrame(parent=Form2)
        self.frame_buttons.setGeometry(QtCore.QRect(410, 390, 210, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.frame_buttons.setFont(font)
        self.frame_buttons.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_buttons.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_buttons.setObjectName("frame_buttons")
        self.pushButton_next = QtWidgets.QPushButton(parent=self.frame_buttons)
        self.pushButton_next.setGeometry(QtCore.QRect(10, 10, 100, 35))
        self.pushButton_next.setObjectName("pushButton_next")
        self.pushButton_cancel = QtWidgets.QPushButton(parent=self.frame_buttons)
        self.pushButton_cancel.setGeometry(QtCore.QRect(120, 10, 80, 35))
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.frame_list = QtWidgets.QFrame(parent=Form2)
        self.frame_list.setGeometry(QtCore.QRect(30, 30, 580, 350))
        self.frame_list.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_list.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_list.setObjectName("frame_list")
        self.label_drops = QtWidgets.QLabel(parent=Form2)
        self.label_drops.setGeometry(QtCore.QRect(30, 30, 580, 350))
        self.label_drops.setStyleSheet("background-color: #ddd; border-radius: 10px")
        self.label_drops.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.label_drops.setObjectName("label_drops")
        self.frame_upload = QtWidgets.QFrame(parent=Form2)
        self.frame_upload.setGeometry(QtCore.QRect(40, 390, 180, 50))
        self.frame_upload.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_upload.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_upload.setObjectName("frame_upload")
        self.pushButton_upload = QtWidgets.QPushButton(parent=self.frame_upload)
        self.pushButton_upload.setGeometry(QtCore.QRect(0, 0, 80, 30))
        self.pushButton_upload.setObjectName("pushButton_upload")
        self.label_upload = QtWidgets.QLabel(parent=self.frame_upload)
        self.label_upload.setGeometry(QtCore.QRect(0, 30, 180, 20))
        self.label_upload.setObjectName("label_upload")

        self.retranslateUi(Form2)
        QtCore.QMetaObject.connectSlotsByName(Form2)

    def retranslateUi(self, Form2):
        _translate = QtCore.QCoreApplication.translate
        Form2.setWindowTitle(_translate("Form2", "自动生成问答对"))
        self.pushButton_next.setText(_translate("Form2", "下一步"))
        self.pushButton_cancel.setText(_translate("Form2", "取消"))
        self.label_drops.setText(_translate("Form2", "<html><head/><body><p align=\"center\"><span style=\"\n"
"                    font-size:12pt;\">选择文档文件，让大模型自动生成问答对</span></p><p align=\"center\"><span\n"
"                    style=\" font-size:12pt; font-weight:700;\">拖动文件到此，或点击选择文件</span></p><p\n"
"                    align=\"center\"><br/></p><p align=\"center\"><span style=\"\n"
"                    font-size:10pt;\">支持doc、docx和pdf非扫描件，</span></p><p align=\"center\"><span\n"
"                    style=\" font-size:10pt;\">一次最大支持选择10个文件，每个文件不超过50MiB</span></p></body></html>\n"
"                "))
        self.pushButton_upload.setText(_translate("Form2", "上传文件"))
        self.label_upload.setText(_translate("Form2", "支持扩展名：.doc .docx .pdf"))
