# Form implementation generated from reading ui file 'ui/Form3.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form3(object):
    def setupUi(self, Form3):
        Form3.setObjectName("Form3")
        Form3.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        Form3.resize(640, 460)
        Form3.setMinimumSize(QtCore.QSize(640, 460))
        Form3.setMaximumSize(QtCore.QSize(640, 460))
        self.frame_buttons = QtWidgets.QFrame(parent=Form3)
        self.frame_buttons.setGeometry(QtCore.QRect(410, 400, 210, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.frame_buttons.setFont(font)
        self.frame_buttons.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_buttons.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_buttons.setObjectName("frame_buttons")
        self.pushButton_next = QtWidgets.QPushButton(parent=self.frame_buttons)
        self.pushButton_next.setGeometry(QtCore.QRect(10, 10, 100, 35))
        self.pushButton_next.setObjectName("pushButton_next")
        self.pushButton_cancel = QtWidgets.QPushButton(parent=self.frame_buttons)
        self.pushButton_cancel.setGeometry(QtCore.QRect(120, 10, 80, 35))
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.frame_list = QtWidgets.QFrame(parent=Form3)
        self.frame_list.setGeometry(QtCore.QRect(30, 40, 580, 350))
        self.frame_list.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_list.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_list.setObjectName("frame_list")
        self.label_hint = QtWidgets.QLabel(parent=Form3)
        self.label_hint.setGeometry(QtCore.QRect(40, 10, 200, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.label_hint.setFont(font)
        self.label_hint.setObjectName("label_hint")

        self.retranslateUi(Form3)
        QtCore.QMetaObject.connectSlotsByName(Form3)

    def retranslateUi(self, Form3):
        _translate = QtCore.QCoreApplication.translate
        Form3.setWindowTitle(_translate("Form3", "自动生成问答对"))
        self.pushButton_next.setText(_translate("Form3", "下载全部"))
        self.pushButton_cancel.setText(_translate("Form3", "关闭"))
        self.label_hint.setText(_translate("Form3", "0 个文档正在生产问答对"))
